#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "planeFunc.h"
#include "objectFunc.h"
#include "titleScreen.h"
#include "youLose.h"

#include "gba.h"
int sprintf(char *str, const char *format, ...);
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WIN,
  LOSE,
  HARD,
};

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;




  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;



  // Load initial application state
  enum gba_state state = START;
  enum gba_state previousState = START;
  drawFullScreenImageDMA(titleScreen);
  setup();
  while (1) {

    currentButtons = BUTTONS; // Load the current state of the buttons

    waitForVBlank();



    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    switch (state) {

      case START:
        waitForVBlank();
        /*if (previousState != START) {
          drawFullScreenImageDMA(titleScreen);
          setup();
        }

         */
        drawFullScreenImageDMA(titleScreen);


        staticMovePlane();
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          state = PLAY;
          initObstacles();
        }
        if (KEY_JUST_PRESSED(BUTTON_B, currentButtons, previousButtons)) {
          state = HARD;
          initHardObs();
        }
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          setup();
          state = START;
        }

        // state = ?
        break;
      case PLAY:
        waitForVBlank();
        fillScreenDMA(BLACK);
        if (vBlankCounter % 63 == 0) {
          planeSprite.playTime++;
        }
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          setup();
          state = START;
        }
        drawPlane();
        movePlane(BUTTONS);
        drawObstacles();

        if (checkCollision() == 1) {
          planeSprite.collected++;
          if (planeSprite.collected == 4) {
            previousState = state;
            state = WIN;
          }
        } else if (checkCollision() == 0) {
          state = LOSE;
        }
        char buffer[20];
        sprintf(buffer, "Collected: %d", planeSprite.collected);
        drawString(140,20,buffer,LIGHT_BLUE);

        // state = ?
        break;
      case WIN:
        waitForVBlank();
        //fillScreenDMA(BLACK);
        drawString(70,100, "YOU WIN", GREEN);

        if (previousState == PLAY) {
          char buf[20];
          sprintf(buf, "Time: %d", planeSprite.playTime);
          drawCenteredString(100,120,5,5,buf, GREEN);
        }

        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          setup();
          state = START;
        }

        // state = ?
        break;
      case LOSE:
        waitForVBlank();
        drawFullScreenImageDMA(youLose);
        //drawString(70, 100, "GAME OVER", BLACK);
        //drawString(80, 90, "PRESS START TO RETRY", BLACK);
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          setup();
          state = START;
        }
        // state = ?
        break;

      case HARD:
        waitForVBlank();
        fillScreenDMA(BLACK);

        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          setup();
          state = START;
        }
        drawPlane();
        movePlane(BUTTONS);
        drawHardObs();

        if (checkHardCollision() == 1) {
          planeSprite.collected++;
          if (planeSprite.collected == 5) {
            previousState = state;
            state = WIN;
          }
        } else if (checkHardCollision() == 0) {
          state = LOSE;
        }
        if (vBlankCounter % 63 == 0) {
          planeSprite.time -= 1;
          vBlankCounter = 0;
        }
        if (planeSprite.time == 0) {
          state = LOSE;
        }
        //char buffer1[20];

        //sprintf(buffer1, "Collected: %d", planeSprite.collected);
        //drawString(140,20,buffer,LIGHT_BLUE);

        char buffer2[20];
        sprintf(buffer2, "Time: %d", planeSprite.time);
        drawString(150,30,buffer2,LIGHT_BLUE);
        break;

    }

    previousButtons = currentButtons; // Store the current state of the buttons

  }

  //UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}
